name: Authorization Checker
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch: {}

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"
  PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
  GITHUB_TOKEN: "${{ secrets.BOT_REPO_PAT }}"

jobs:
  trigger:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.11"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Clone repository
        with:
          token: "${{ secrets.BOT_REPO_PAT }}"

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install dead-hosts-launcher
          pip install --upgrade PyFunceble-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Get Launcher version
        run: |
          dead-hosts-launcher --version

      - name: Run Launcher
        run: |
          dead-hosts-launcher --authorize
